[program:umbralia-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/umbralia/current/artisan queue:work redis --queue=default --sleep=3 --tries=3 --timeout=90
directory=/var/www/umbralia/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/umbralia/current/storage/logs/worker.log
stopwaitsecs=3600
